deploy_staging:
  type: deploy
  environment:
    name: staging
    url: example.com
  script:
    - ssh root@103.31.39.134 "cd /home/digicert/mysql/digital-certificate-be && git checkout master && git pull origin master && docker-compose down --rmi local && docker-compose up -d exit"
  only:
    - master