version: '3'
services:
  digital-certificate-be:
    container_name: digital-certificate-be
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ../env/digital-certificate-be.env
    volumes:
      - /home/ubuntu/file_directory/images:/file_directory/images